-- ITEM LIST FILE EXAMPLE

local Items = {
	{
		id = 1,
		name = "Air"
	}, -- THAT IS REQUIRED TO SERVICE WORK NORMALLY
	{
		id = 2,
		name = "Sword",
		image = "rbxassetid://87419755911673",
		stacked = false
	},
	{
		id = 3,
		name = "Hammer",
		image = "rbxassetid://125062786897130",
		stacked = false
	},
	{
		id = 4,
		name = "Diamond",
		image = "rbxassetid://88317141923825",
		stacked = true
	},
	{
		id = 5,
		name = "Mega_Diamond",
		image = "rbxassetid://94946684477021",
		stacked = false
	}
}

return Items
